import Footer  from "../../../layouts/footer";
import Header  from "../../../layouts/header";
import Wrapper from "../../../layouts/wrapper";

export default function Conditions(){
    return(
        <>
            <head>
                <title>Termos de uso | Mixservlog</title>
            </head>
            <Header />
            <Wrapper>
                <section className="h-full">
                    <div>
                        <h1 className="text-3xl font-bold">Termos de Uso</h1>
                    </div>
                    <div className="mt-5">
                        <p>Termos de Uso Mix Serviços Logísticos Eireli para (Entregadores Parceiros)</p>
                        Estes Termos de Uso Mix Delivery para Entregadores (“Termos de Uso”) regula os termos de acesso ou uso por você (“Entregador Parceiro”) da plataforma de serviços de informação (“Plataforma”) por meio de aplicativos móveis, aplicativos de sites (em conjunto, “Aplicativos”) ou sites para receber os serviços disponibilizados por Mix Serviços Logísticos Eireli, com sede na Cidade de São Paulo, na Av. Dr. Gastão Vidigal 1132, sala: 309- Vila Leopoldina, Estado de São Paulo, CEP: 05314-000, inscrita no CNPJ/MF sob o nº 40.107.044/0001-30. 
                        Por favor, leia atentamente a estes Termos de Uso, expressos ou referenciados neste instrumento antes de acessar ou usar a Plataforma. Este Termos de Uso é um contrato legalmente vinculante que estabelece os direitos e obrigações entre a Mix Drive e você, o Entregador Parceiro. 
                        Ao acessar ou usar a Plataforma, você expressamente declara, pelo presente, que:
                        você leu e entendeu estes Termos de Uso;
                        você cumprirá estes Termos de Uso;
                        você reconhece e concorda com a Política de Privacidade;
                        você tem pelo menos a maioridade legal no seu local de residência e é legalmente competente para celebrar contratos;
                        você está devidamente autorizado a conduzir e possui uma licença válida emitida por uma autoridade competente para a categoria e o tipo de veículo apropriados, quando aplicável; e você tem poderes para celebrar estes Termos de Uso pessoalmente e, caso aplicável, em nome de qualquer organização em cujo nome você se inscreveu para uso da Plataforma e para sujeitar tal organização a estes Termos de Uso.
                        SE VOCÊ NÃO CONCORDAR COM QUALQUER DESTES TERMOS DE USO, POR FAVOR NÃO ACESSE OU USE A PLATAFORMA. POR FAVOR, LEIA COM ATENÇÃO “ISENÇÃO DE RESPONSABILIDADE” E “INDENIZAÇÃO”. ESTAS DISPOSIÇÕES LIMITAM NOSSA RESPONSABILIDADE PERANTE A VOCÊ.
                        Nestes Termos de Uso, “Lei Aplicável” significa leis, normas e regulamentos brasileiros aplicáveis, e regulamentos regendo pagamentos e serviços sob este instrumento, incluindo, normas, regulamentos, orientações regulatórias, diretivas, políticas, ordens ou determinações de (ou acordos com), e instruções por escrito obrigatórias de (ou acordos com) qualquer autoridade reguladora, sendo que que cada um dos itens anteriores poderá ser alterado de tempos em tempos e passará a vigorar.
                        A Mix Delivery se reserva o direito de alterar estes Termos de Uso de tempos em tempos. Se fizermos alterações, informaremos a você alterando a data no topo dos Termos de Uso e, em alguns casos, forneceremos a você um aviso adicional (como acrescentar uma declaração à nossa página inicial ou enviar uma notificação por e-mail). Nós o encorajamos a revisar estes Termos de Uso periodicamente para se manter informado sobre nossas práticas. Sempre que fizermos alterações a estes Termos de Uso, eles entram em vigor quando os Termos de Uso revisados forem publicados, salvo se nós informarmos a você de outra forma. Se você continuar a usar a Plataforma após a publicação dos Termos de Uso revisados, isto será considerado como sua aceitação das alterações a estes Termos de Uso.
                        1. NOSSOS SERVIÇOS
                        Os serviços prestados pela Mix Delivery (“Serviços”) se destinam a conectar os demandantes de transporte e/ou serviços de logística (incluindo, mas não se limitando a pequenas empresas, clientes comerciais e clientes individuais, coletivamente “Usuários”) e Entregadores Parceiros que prestem serviços de transporte e/ou de logística (“Entrega de Remessas”) através da Plataforma. Você reconhece e concorda que a Mix Delivery só fornece a você e aos Usuários serviços neutros de informação para conexão de terceiros independentes. A Entrega da Remessa realizada pelos Entregadores Parceiros não será considerada realizada pela Mix Delivery. A Mix Delivery não é responsável pelos atos e/ou omissões de quaisquer Entregadores Parceiros, e qualquer responsabilidade em relação à Entrega de Remessas será exclusivamente dos Entregadores Parceiros.
                        Você afirma que sua relação com a Mix Delivery é independente, e não uma relação entre empregador e empregado. Além disso, nenhuma relação de joint venture, parceria, emprego ou de agência é criada entre os Entregadores Parceiros e a Mix Delivery como resultado destes Termos de Uso ou do uso da Plataforma. Mesmo que um Entregador Parceiro escolha, por sua própria vontade, a usar sinalização, adesivo ou crachá de identificação da Mix Delivery, o Entregador Parceiro concorda que tal decisão foi por sua conta própria e que não é exigida pela Mix Delivery, e o Entregador Parceiro reconhece que o uso de qualquer sinalização, adesivo ou crachá de identificação não levará a conclusão de ser um empregado.
                        2. USO DO SOFTWARE
                        Ao usar o software fornecido pela Mix Delivery (“Software”), você concorda que:
                        você não tem permissão para alugar, arrendar, sublicenciar, distribuir ou transferir cópias do Software ou a licença de uso do Software para terceiros;
                        você não poderá sondar, examinar ou testar a vulnerabilidade da Plataforma ou de qualquer rede conectada à Plataforma, nem violar as medidas de segurança ou de autenticação na Plataforma ou em qualquer rede conectada à Plataforma;
                        você não poderá modificar, adaptar, fazer engenharia reversa, decompilar, desmontar, traduzir o Software ou criar trabalhos derivados baseados no Software;
                        você não poderá interromper a operação normal do Software ou usar quaisquer métodos para exportar ou modificar o código-fonte do Software;
                        você não poderá fazer upload ou enviar qualquer tipo de vírus de computador, worms, cavalos de troia ou códigos maliciosos;
                        você não poderá instalar e/ou executar o Software em qualquer dispositivo que não o dispositivo móvel executando os sistemas operacionais aprovados pela Mix Delivery; e além da licença de uso do Software concedida por este instrumento, nenhuma outra licença ou direito é concedida a você e a propriedade do Software e todos os outros direitos são, pelo presente, expressamente reconhecidos como sendo da Mix Delivery e de seus fornecedores.

                        3. CONTA DE ENTREGADOR PARCEIRO
                        Como requisito ao uso dos Serviços, você deverá se registrar para uma conta de Entregador Parceiro (“Conta de Entregador Parceiro”) na Mix Delivery. Assim que o seu registro for concluído com sucesso junto a Mix Delivery, uma Conta de Entregador Parceiro será fornecida a você, acessível com uma senha de sua escolha.
                        Ao se registrar, você é obrigado a fornecer suas informações pessoais, como nome, foto, informações de contato direto ou indiretamente, de acordo com a Política de Privacidade da Mix Delivery. Você concorda que os detalhes incluídos e mantidos por você são precisos, completos e válidos. A Mix Delivery não se responsabiliza por informações de registro falsas, incompletas, antigas ou incorretas fornecidas por você. A sua falha em incluir ou manter informações precisas, completas e válidas poderá resultar em sua incapacidade de acessar e usar os Serviços. Você é o único responsável por todas as atividades que ocorrerem em sua conta de Entregador Parceiro. A Mix Delivery terá o direito de verificar as informações que você forneceu em todos os momentos e recusar o uso dos Serviços sem fornecer os motivos e aviso prévio.
                        Você é responsável por adquirir e atualizar hardware ou dispositivos compatíveis necessários para o acesso e a utilização dos Serviços. A Mix Delivery não garante que os Serviços, ou qualquer parte deles, funcionem em qualquer hardware ou dispositivo específico. A Mix Delivery se reserva o direito de encerrar o uso dos Serviços se você estiver usando o Serviço em um dispositivo incompatível ou não autorizado ou se a segurança de sua Conta de Entregador Parceiro tiver sido comprometida de qualquer forma ou por qualquer motivo que possamos achar justo.
                        Ao usar os Serviços, você concorda que:
                        você só deverá acessar os Serviços usando meios explicitamente autorizados pela Mix Delivery;
                        a Plataforma e os Serviços fornecidos serão usados ​​exclusivamente por você, para seu uso pessoal, e não serão revendidos a terceiros;
                        você não autorizará terceiros a usar sua conta de Entregador Parceiro;
                        você só tem permissão para abrir uma única conta de Entregador Parceiro;
                        a transferência de sua conta de Entregador Parceiro para qualquer outra pessoa física ou jurídica não é permitida;
                        você não poderá usar uma conta que está sujeita a quaisquer direitos de uma pessoa que não seja você sem a autorização apropriada;
                        os Serviços não podem ser usados ​​para fins ilegais, incluindo, mas não se limitando a (i) violação de Lei Aplicável; (ii) armazenamento ou envio de qualquer material ilegal; (iii) compartilhamento de informações pessoais sensíveis de terceiros, sem o seu consentimento (iv) causar dano intencional, perturbação, inconveniência ou aborrecimento; (v) comprometer ou prejudicar a operação adequada dos Serviços; (vi) se passar por outra pessoa; ou (vii) copiar ou distribuir os Serviços sem a permissão da Mix Delivery;
                        sua senha ou quaisquer credenciais de identificação que a Mix Delivery fornecer a você devem ser seguras e confidenciais;
                        prova de identificação ou outros documentos devem ser apresentados imediatamente caso sejam solicitados pela Mix Delivery;
                        o cumprimento de todas as Leis Aplicáveis ​​é uma obrigação durante o uso dos Serviços;
                        você não deverá usar qualquer “link direto”, “coleta de dados web”, “robô”, “spider” ou outro dispositivo automático, programa, algoritmo ou metodologia, ou qualquer processo manual semelhante ou equivalente, para acessar, adquirir, copiar ou monitorar qualquer parte da Plataforma ou qualquer conteúdo, ou de qualquer forma reproduzir ou contornar a estrutura de navegação ou apresentação da Plataforma ou qualquer conteúdo, para obter ou tentar obter quaisquer materiais, documentos ou informações por qualquer meio não disponibilizado propositalmente por meio da Plataforma. A Mix Delivery se reserva o direito de impedir qualquer atividade desse tipo;

                        você não deverá tentar interferir, comprometer a integridade ou segurança do sistema ou decifrar quaisquer transmissões de ou para os servidores que executam a Plataforma;
                        você não deverá coletar ou colher nenhuma informação de identificação de indivíduos, incluindo nomes de contas, da Plataforma; e
                        você não deverá realizar ameaças, assédio, discriminação (com base em raça, sexo, idade, deficiência ou qualquer outra classificação protegida) ou praticar qualquer outro comportamento que a Mix Delivery considere impróprio durante o uso dos Serviços.
                        você se compromete com as Diretrizes Comunitárias. Qualquer violação estará sujeita a bloqueio, suspensão ou término de sua conta.
                        você deve cumprir as diretrizes adicionais para ser um Entregador Parceiro da Mix Delivery:
                        a) O dispositivo móvel usado para prover os seus serviços de trabalho não deve ser o mesmo aparelho que o de usuário para solicitar corridas de Entregadores Parceiros.
                        b) O Entregador Parceiro não deve possuir antecedentes criminais.
                        c) Não utilize aparelhos para instalar o aplicativo da Mix Delivery ou números de celulares ou aparelhos que já tenham sido bloqueados por qualquer motivo por fraude.
                        d) Não faça transações com Usuários que não sigam as Diretrizes da Plataforma.
                        e) Não faça transações fora da Plataforma utilizando o nome da Mix Delivery.
                        f) Se houver qualquer problema com a entrega, a Mix Delivery fará duas tentativas de contato telefônico no número de celular registrado por você na Plataforma. Se não tivermos o seu retorno, sua conta será temporariamente suspensa. Você terá 3 dias úteis para contatar a Mix Delivery para esclarecer os fatos. Após o período de 3 dias, sua conta será bloqueada.
                        g) Mantenha seus documentos pessoais e do seu veículo atualizados na plataforma.
                        Qualquer violação das diretrizes acima dos Termos de Uso ocasionarão no bloqueio, suspensão ou término de sua conta de Entregador Parceiro. Se isso ocorrer, você será notificado, de acordo com a lei vigente. A Mix Delivery poderá, ainda, reportar os atos ilegais para as autoridades competentes.
                        4. GARANTIAS E DECLARAÇÕES DE ENTREGADORES PARCEIROS
                        Você, como Entregador Parceiro faz, por meio deste e de forma irrevogável, as seguintes garantias e declarações:
                        Após obter as informações dos Usuários e das entregas, o Entregador Parceiro deverá verificar por si mesmo essas informações. O Entregador Parceiro deverá tomar a decisão de aceitar e fornecer a Entrega de Remessas a seu próprio critério, depois de verificar adequadamente as informações obtidas;
                        O Entregador Parceiro entende e concorda que é responsável por cumprir todos os cronogramas de entrega estabelecidos entre ele e o Usuário. O Entregador Parceiro fará todos os esforços razoáveis ​​para entregar a remessa de acordo com os respectivos cronogramas de entrega estabelecidos com o Usuário;
                        Você será exclusivamente responsável por todas e quaisquer reclamações, ações e responsabilidades resultantes de qualquer acidente, perda ou dano, incluindo, mas não se limitando a, lesão corporal, morte, perda total e danos materiais causados pela ou alegadamente resultantes de Entrega de Remessas fornecida por você;
                        Você será responsável pelo conteúdo de todas as remessas e por todos os danos ou perdas nas remessas no momento da entrega. O Entregador Parceiro deverá tomar todas as precauções razoáveis ​​para evitar que pessoas não autorizadas tenham acesso à remessa e deverá tomar todas as precauções razoáveis ​​contra a perda da ou dano à remessa;
                        Você deverá, em todos os momentos enquanto estiver realizando Entrega de Remessas, possuir uma carteira de motorista válida e todas as outras licenças, permissões, registros, aprovações e/ou autorizações exigidas para fornecer Entrega de Remessas dentro da jurisdição em que você foi registrado pela Mix Delivery para realizar Entrega de Remessas. Para que a Mix Delivery cumpra todas as obrigações aplicáveis ​​a ela, você, mediante solicitação da Mix Delivery, fornecerá cópias na forma exigida por nós de todas as licenças, permissões, registros, aprovações e/ou autorizações exigidas, conforme solicitado de tempos em tempos;

                        Além da Plataforma, você será responsável por prover todos os equipamentos necessários para a realização das Entrega de Remessas. Você deverá ser titular ou ter direitos suficientes sobre o equipamento que usará para realizar as Entrega de Remessas. O Entregador Parceiro é exclusivamente responsável por realizar a manutenção de todos esses equipamentos e garantir que eles estejam em conformidade com todos os padrões legais, de segurança e de qualidade. Exceto quando exigido de outra forma pelas Leis Aplicáveis, o Entregador Parceiro assume todos os riscos de danos ou de perda de seu equipamento;
                        Com exceção do serviço de entregas a pé, você não deverá usar um veículo diferente do seu veículo registrado para realizar a Entrega de Remessas, que deverá sempre atender a todos os padrões aplicáveis ​​do veículo, atualizados de tempos em tempos, inclusive possuindo certificação de inspeção técnica aplicável em sua jurisdição. Você deverá usar veículos em boas condições de operação e em conformidade com todas as Leis Aplicáveis. Você deverá guardar todos os registros e inspeções do veículo e fornecer a versão mais recente de tais registros mediante solicitação;
                        Você deverá sempre cumprir, às suas custas, suas obrigações legais em relação a seguro (incluindo, mas não se limitando a seguro obrigatório de veículos motorizados contra terceiros para qualquer veículo usado para a realização de Entrega de Remessas (caso aplicável)) e manter, às suas custas, outras apólices que alguém realizando Entrega de Remessas prudentemente manteria, bem como qualquer outra cobertura de seguro mínima que a Mix Delivery solicite que você mantenha, incluindo, mas não se limitando a uma apólice de seguro de veículo motorizado contra terceiros válida com disposições para cobrir o uso comercial do veículo, e uma apólice de seguro de responsabilidade civil geral em níveis que satisfaçam:
                        os requisitos mínimos aplicáveis à operação de veículos de entrega de mercadorias em vias públicas na jurisdição em que você está registrado para realizar Entrega de Remessas;
                        a realização de Entrega de Remessas e quaisquer outros serviços contemplados por estes Termos de Uso; e
                        quaisquer outras normas mínimas impostas pela Mix Delivery (conforme informado pela Mix Delivery de tempos em tempos).
                        Para que a Mix Delivery confirme sua conformidade contínua com esses requisitos, você, mediante solicitação da a Mix Delivery, fornecerá cópias de quaisquer apólices de seguro relevantes e certificados de vigência de seguro ou outro comprovante de seguro equivalente. Se, a qualquer momento, você deixar de possuir uma apólice de seguro exigida, você deverá notificar imediatamente a Mix Delivery sobre esta mudança em suas circunstâncias e interromper o fornecimento de Entrega de Remessas;

                        

                        Você deverá obedecer a todas as Leis Aplicáveis ​​relacionadas à Entrega de Remessas e será o único responsável por quaisquer violações de tais Leis Aplicáveis. Você não deverá aceitar quaisquer solicitações em que a natureza da entrega seja exclusivamente a movimentação de passageiros;
                        Durante o curso do seu trabalho, a Mix Delivery o aconselha a seguir e cumprir as seguintes diretrizes (“Diretrizes de Entrega da a Mix Delivery”): Diretrizes da Comunidade
                        Os Entregadores Parceiros serão exclusivamente responsáveis por se familiarizarem com as Diretrizes de Entrega da a Mix Delivery, conforme aditadas de tempos em tempos. Salvo se de outro modo estabelecido nas Diretrizes de Entrega da Mix Delivery e nestes Termos de Uso, qualquer conduta contra as Diretrizes de Entrega da Mix Delivery constituirá uma violação destes Termos de Uso, dando a Mix Delivery o direito de bloquear temporariamente ou desativar permanentemente sua conta de Entregador Parceiro.
                        A a Mix Delivery se reserva o direito de suspender o processamento de qualquer transação que razoavelmente acredite possa ser fraudulenta, ilegal ou envolver qualquer atividade criminosa ou onde você e/ou o Usuário tenham violado qualquer disposição deste Termos de uso.
                        O Entregador Parceiro reconhece que, durante o curso de seu trabalho, poderá ter acesso a informações confidenciais, propriedade privada, segredos comerciais, informações protegidas de saúde e/ou de identificação pessoal, de terceiros ou de Usuários (“Informações Confidenciais”). Essas informações incluem, mas não estão limitadas a, informações sobre o Usuário, negócios do Usuário e o conteúdo das remessas, endereço do Usuário, informações de contato do Usuário, endereço de entrega, informações de pagamento, formas de pagamento, informações de cartão de crédito, contas financeiras, informações demográficas, endereço comercial, informações sobre sócios, colaboradores, clientes do Usuário e informações semelhantes sobre o recipiente da entrega. O Entregador Parceiro concorda que manterá a confidencialidade de todas as Informações Confidenciais e não as divulgará a qualquer outra pessoa, exceto conforme necessário para realizar as Entregas de Remessas ou conforme exigido por lei. A divulgação não autorizada de tais Informações Confidenciais constituirá uma violação substancial destes Termos de Uso, dando à Mix Delivery o direito de bloquear temporariamente ou desativar permanentemente sua Conta de Entregador Parceiro.
                        Caso o Entregador Parceiro viole qualquer uma das garantias e declarações acima, a Mix Delivery terá o direito de bloquear temporariamente ou desativar permanentemente sua conta de Entregador Parceiro. O Entregador Parceiro deverá arcar com todos os danos ou perdas decorrentes. O Entregador Parceiro também deverá indenizar a Mix Delivery, suas coligadas, seus sócios e/ou qualquer outro terceiro por danos suportados em razão da falha do Entregador Parceiro em cumprir com as garantias e declarações acima.

                        5. PAGAMENTO
                        O Entregador Parceiro reconhece que os Usuários - não a Mix Delivery - são responsáveis ​​por pagar todas as despesas e taxas associadas à entrega. Uma vez que o Usuário e o Entregador Parceiro tenham verificado que as entregas foram concluídas, a conta de pagamento do Usuário será cobrada. A Mix Delivery se reserva o direito de alterar os preços praticados a qualquer momento, a seu critério. O Entregador Parceiro reconhece e concorda que qualquer pagamento recebido pela Mix Delivery é devido ao serviço de informação fornecido pela Plataforma.
                        A Mix Delivery se reserva o direito de suspender o processamento de qualquer transação que razoavelmente acredite possa ser fraudulenta, ilegal ou envolver qualquer atividade criminosa ou onde você e/ou o Usuário tenham violado qualquer disposição deste Termos de uso. Nesse caso, você não poderá responsabilizar a Mix Delivery por qualquer retenção, atraso, suspensão, perda ou cancelamento de qualquer pagamento a você.
                        A Mix Delivery fará os pagamentos para você e por você por meio de um sistema de carteira. O saldo da carteira do Entregador Parceiro poderá ser transferido por você para a conta bancária indicada. A Mix Delivery se reserva o direito de fazer deduções relevantes do saldo da sua carteira com base em nossos Termos de Uso, Diretrizes de Entrega da Mix Delivery, conforme autorizado por você ou notificado a você através de nossa Plataforma.
                        Os depósitos de garantia asseguram os direitos dos Entregadores Parceiros. Consulte nossa Política de Depósito de Garantia aqui. O Entregador Parceiros será exclusivamente responsável por se familiarizar com a Política de Depósito de Garantia antes de pagar o depósito de garantia.
                        Como um Entregador Parceiro, dependendo dos serviços solicitados por nossos Usuários, você poderá ser elegível a receber uma combinação das tarifas listadas abaixo:
                        Tarifa
                        Tarifas básicas - É a tarifa de distância incorrida durante a Entrega de Remessas.
                        Subsídios de pedidos - São os subsídios pagos pela Mix Delivery e estão incluídos como parte da tarifa básica, subsídios não limitados aos subsídios de demanda de pico.

                        Cupom Mix Delivery - É o valor da promoção aplicada a um pedido específico. As promoções são normalmente dadas aos Usuários e subsidiadas pela Mix Delivery.
                        Taxas e outras cobranças
                        Taxa de prioridade - São as taxas adicionais que um Usuário se comprometeu a pagar antes da Entrega de Remessas com o objetivo de encorajar a entrega rápida.
                        Taxa de espera - São as taxas adicionais impostas a um pedido específico em que os Entregadores Parceiros tenham recebido solicitação do Usuário de aguardar o recebimento ou a entrega das mercadorias.
                        Sobretaxa de alta demanda - São as taxas adicionais impostas a um pedido específico para incentivar a Entrega de Remessas em horários de pico. A Mix Delivery se reserva o direito de definir as horas de super pico com base em necessidades operacionais.
                        Taxa de CBD - São encargos incorridos ao entrar em zonas designadas durante a Entrega de Remessas. A Mix Delivery se reserva o direito de definir tais zonas com base em necessidades operacionais.
                        Sobretaxa mínima - É a diferença entre a tarifa calculada e as tarifas mínimas pré-determinadas. A Mix Delivery se reserva o direito de alterar as tarifas mínimas de tempos em tempos.
                        Taxas de pedágio - São as taxas de túnel e de pedágio incorridas por você durante a Entrega de Remessas. Isso deverá ser cobrado com base no custo real e deve ser mutuamente acordado com o Usuário.
                        Encargos do pedido - São as outras taxas e sobretaxas relacionadas aos serviços de valor agregado solicitados pelo Usuário. Esta categoria inclui itens, mas não se limita a, taxas de movimentação, sobretaxas de serviço de compra, etc.
                        Iniciativas Mix Delivery
                        Taxa de Adesivagem – É o valor que a a Mix Delivery paga a você em troca de você concordar em adesivar o seu veículo com adesivos de nossa marca. As dimensões, o modelo e a posição do adesivo no veículo serão determinados pela Mix Delivery. Você também concorda em cooperar com a verificação de adesivagem pela Mix Delivery quando solicitado. O não cumprimento poderá levar à perda da taxa de adesivagem.
                        Campanha de indicação de usuários por motoristas - É uma campanha onde você receberá recompensas monetárias após indicações bem-sucedidas de usuários que utilizem a plataforma a Mix Delivery pela primeira vez. Você receberá um código de promoção exclusivo se optar por esta campanha, onde será incentivado a distribuir esse código a terceiros. Em caso do uso bem-sucedido do código promocional para um pedido concluído originado de um novo usuário, você será recompensado de acordo com as taxas definidas pela Mix Delivery. A Mix Delivery se reserva o direito de revogar recompensas se acreditarmos razoavelmente que houve tentativas de fraudar a Mix Delivery por meio desta campanha.
                        6. COMUNICAÇÃO
                        Ao criar uma Conta de Entregador Parceiro, você concorda, eletronicamente, em aceitar e receber comunicações da Mix Delivery, incluindo via e-mail, mensagem de texto, ligações e notificações push para o dispositivo móvel ou número de telefone celular que você fornecer à Mix Delivery. Você entende e concorda que poderá receber comunicações geradas por sistemas de discagem automática de telefone e/ou que entregarão mensagens pré-gravadas enviadas por ou em nome da Mix Delivery, suas empresas coligadas e/ou prestadores de serviços terceirizados, incluindo, mas não se limitando a, comunicações relativas a pedidos aceitos por meio de seu registro com relação aos Serviços. Você poderá cancelar o recebimento alterando suas preferências de notificação. É importante ter presente que a desativação poderá afetar o uso dos Serviços.
                        7. PROMOÇÕES
                        Para o benefício mútuo de a Mix Delivery e de todos os Entregadores Parceiros, incluindo você, de tempos em tempos, a Mix Delivery poderá oferecer promoções em seu nome para alguns ou todos os Usuários, o que pode ocasionar que Usuários paguem a você uma quantia menor do que a habitual, e quando uma promoção for aplicável, você concorda em fornecer a Entrega de Remessas para os Usuários no valor mais baixo. Quando uma promoção se aplicar e quando aplicável, a Mix Delivery irá reduzir o valor de suas taxas em um montante igual ao valor das promoções.
                        8. OUTRAS INTERAÇÕES COM TERCEIROS
                        Ao usar ou acessar a Plataforma, você poderá se comunicar com comprar bens e/ou serviços, ou participar de promoções de prestadores de serviços terceirizados, anunciantes ou patrocinadores mostrando seus produtos e/ou serviços através da Plataforma. Qualquer atividade, e quaisquer termos, condições, garantias ou declarações associadas a tal atividade, se dará exclusivamente entre você e tal terceiro. A Mix Delivery e seus licenciadores não terão qualquer dever, obrigação ou responsabilidade por qualquer comunicação, compra, transação ou promoção entre você e qualquer terceiro. A Mix Delivery não terá qualquer responsabilidade ou obrigação decorrente de quaisquer acordos entre você e esses fornecedores terceiros.

                        9. DIREITOS DE PROPRIEDADE INTELECTUAL
                        Somente a Mix Delivery (e seus licenciadores, quando aplicável) deterá todos os direitos, a propriedade e interesse, incluindo todos os direitos de propriedade intelectual relacionados, sobre e em relação a Plataforma e os Serviços. Estes Termos de Uso não constituem uma venda e não transferem a você quaisquer direitos de propriedade ou outros direitos relacionados à Plataforma e aos Serviços, ou quaisquer direitos de propriedade intelectual pertencentes à a Mix Delivery. Nomes de empresas, logotipos e nomes de produtos associados à Plataforma e aos Serviços são marcas registradas e/ou propriedade intelectual da a Mix Delivery ou de terceiros, e nenhum direito ou licença é concedido para usá-los. Você concorda em não remover, alterar ou ocultar qualquer direito autoral, marca registrada, marca de serviço ou outros avisos de direitos de propriedade incorporados ou existentes na Plataforma e nos Serviços.
                        Ao fornecer conteúdo, informações ou materiais (“Conteúdo do Entregador Parceiro”) para Mix Delivery, você concede à Mix Delivery uma licença global, perpétua, irrevogável, transferível e livre de royalties, com o direito de sublicenciar, usar, copiar, modificar, criar trabalhos derivados de, distribuir, exibir publicamente, executar publicamente e de outra forma explorar de qualquer maneira tal Conteúdo de Entregador Parceiro em todos os formatos e canais de distribuição agora conhecidos ou criados no futuro, sem necessidade de aviso prévio a você ou consentimento adicional de sua parte você, e sem a exigência de pagamento a você ou qualquer outra pessoa ou entidade.
                        Você reconhece que a Mix Delivery atua apenas como um canal passivo para a distribuição do Conteúdo do Entregador Parceiro e não é responsável perante a você ou a terceiros pelo conteúdo ou precisão do Conteúdo do Entregador Parceiro. A Mix Delivery não irá monitorar continuamente o Conteúdo de Entregador Parceiro publicado por você, nem terá a obrigação de fazê-lo. Sem limitar o precedente, você reconhece e concorda que quaisquer observações, opiniões, comentários, sugestões e outras informações expressas ou incluídas no Conteúdo de Entregador Parceiro não representam necessariamente as da Mix Delivery.
                        Qualquer uso por você do Conteúdo do Entregador Parceiro será inteiramente por sua própria conta e risco. Você declara e garante que qualquer Conteúdo do Entregador Parceiro postado ou transmitido por você é original e não copia o trabalho de terceiros ou viole quaisquer direitos de propriedade intelectual de terceiros, direitos de privacidade ou direitos de personalidade, e não contém qualquer conteúdo difamatório ou declarações depreciativas. Além disso, você declara e garante que tem a capacidade de conceder a licença conforme estipulado neste parágrafo.

                        

                        Você concorda em indenizar e manter a Mix Delivery, suas coligadas e licenciadores indenes contra todos os custos, despesas, danos, perdas e responsabilidades incorridas ou sofridas pela Mix Delivery ou suas empresas coligadas relacionadas a qualquer Conteúdo do Entregador Parceiro postado ou transmitido por você ou seu outro uso do site, do Serviço ou da Plataforma.
                        A Mix Delivery se reserva o direito, a seu exclusivo critério, de bloquear ou remover (no todo ou em parte) qualquer Conteúdo do Entregador Parceiro postado ou transmitido por você e que a Mix Delivery acredite não estar de acordo com estes Termos de Uso (incluindo materiais que violem ou possam violar direitos de propriedade intelectual, direitos de privacidade ou direitos de personalidade de terceiros), ou que sejam de outro modo inaceitáveis para nós.
                        A Mix Delivery respeita seus direitos às suas ideias, por favor não envie quaisquer ideias, informações ou sugestões confidenciais de qualquer forma à Mix Delivery ou a qualquer uma das suas coligadas. Com relação a todas as ideias, informações ou sugestões que você enviar, independentemente do que diga sua comunicação sobre seus envios, você entende que seus envios são voluntários e os seguintes termos se aplicam aos seus envios: (i) o material enviado e seu conteúdo será automaticamente propriedade da a Mix Delivery, sem que qualquer pagamento seja devido a você; (ii) a Mix Delivery não terá obrigação de revisar o material enviado; (iii) a Mix Delivery poderá implementar e distribuir qualquer parte do material enviado e seu conteúdo para qualquer propósito e de qualquer forma, sem que qualquer pagamento seja devido a você; e (iv) a Mix Delivery não terá obrigação de manter a confidencialidade do material enviado por você;
                        Você poderá usar as informações da Plataforma disponibilizadas propositalmente pela Mix Delivery para download através da Plataforma, desde que você:
                        não remova qualquer linguagem de aviso de propriedade em todas as cópias de tais documentos e não faça nenhuma modificação nas informações;
                        use essas informações apenas para fins informativos pessoais e não comerciais e não copie ou publique tais informações em qualquer computador em rede ou as transmita em qualquer mídia; e
                        não faça quaisquer declarações ou garantias adicionais relacionadas a tais informações.


                        10. INDENIZAÇÃO 
                        O Entregador Parceiro reconhece que o Entregador Parceiro é responsável por todas as remessas e todas as Entregas de Remessa durante o transporte das remessas. O Entregador Parceiro concorda que a Mix Delivery não tem controle ou responsabilidade sobre remessas ou Entregas de Remessas e apenas tem controle ou responsabilidade pelo funcionamento da Plataforma. O Entregador Parceiro concorda que a Mix Delivery não será responsável por quaisquer ações, ilícitos, perdas ou danos sofridos pelo Entregador Parceiro, exceto se tal ação for uma infração intencional destes Termos de Uso ou negligência grosseira.
                        O Entregador Parceiro concorda em defender, indenizar e isentar de responsabilidade a Mix Delivery, seus sucessores passados ​​e presentes, cessionários, coligadas, diretores, proprietários, funcionários e procuradores (“Partes Indenizadas da Mix Delivery”) de todas e quaisquer perdas, processos reais ou ameaças de processos, ações, reclamações, demandas (com base na lei ou na equidade), reivindicações, danos, pedidos de pagamento, condenações, multas, julgamentos, acordos, responsabilidades, custos e despesas (incluindo honorários advocatícios razoáveis, custos, penalidades, juros e pagamentos) decorrentes de ou incorridos em conexão com reivindicações feitas por terceiros contra um Parte Indenizada da Mix Delivery decorrentes direta ou indiretamente de, ou como resultado de ou em conexão com, a violação pelo Entregador Parceiro (i) destes Termos de Uso; (ii) da conduta em relação à Plataforma, Serviços e/ou Entrega de Remessas; (iii) da violação ou alegada violação de qualquer lei ou dos direitos de terceiros, incluindo, sem limitação, os de outros Entregadores Parceiros, de Usuários, motoristas, funcionários, subcontratados, cessionários e pedestres; (iv) da divulgação de “Informações Confidenciais”; (v) da propriedade, uso ou operação de qualquer veículo utilizado na Entrega da Remessas; (vi) da não manutenção de apólices de seguro, licenças, permissões ou autorizações adequadas; (vii) de quaisquer danos ou perdas resultantes do trabalho e ou da conduta do Entregador Parceiro e/ou do trabalho do Entregador Parceiro com terceiros e/ou Usuários, incluindo, mas não se limitando a, danos às remessas; (viii) de ilícitos, violação da política, violação da lei ou outra conduta inadequada e (ix) de falha ou suposta falha no pagamento de todos os impostos, retenções na fonte, contribuições de seguro ou prêmios exigidos. De acordo com a obrigação do Entregador Parceiro em defender a Mix Delivery, a Mix Delivery terá o direito de usar seus próprios advogados.
                        O Entregador Parceiro concorda em realizar Entregas de Remessas em conformidade com todas as Leis Aplicáveis ​​e deve defender, indenizar e isentar de responsabilidade a Mix Delivery por qualquer violação ou alegada violação pelo Entregador Parceiro de tais leis. A Mix Delivery se reserva o direito de bloquear, suspender ou encerrar o acesso à Plataforma por um Entregador Parceiro por quaisquer violações destes Termos de Uso ou qualquer outra conduta considerada inadequada pela Mix Delivery. No caso improvável de a condição do Entregador Parceiro como um prestador de serviços independente ser contestado, e o Entregador Parceiro não for considerado, por um tribunal, agência ou árbitro como um prestador de serviços independente, o Entregador Parceiro concorda em defender, indenizar e isentar de responsabilidade a Mix Delivery de todos os custos, penalidades, impostos retroativos, danos e honorários advocatícios associados a tal determinação. De acordo com a obrigação do Entregador Parceiro em defender a Mix Delivery, A Mix Delivery terá o direito de usar seus próprios advogados.
                        O Entregador Parceiro concorda e reconhece que não irá e não poderá responsabilizar a Mix Delivery por quaisquer questões além do controle direto de a Mix Delivery, incluindo quaisquer atos fortuitos, perda de energia, interrupção de energia, desligamento ou dificuldades técnicas com a Plataforma, manutenção do sistema, falha de outra recepção de celular, falha de outros prestadores de serviço, cancelamento de serviços por terceiros, pandemia, epidemias, surtos, a pandemia de COVID 19, greves, disputas trabalhistas, distúrbios civis, hostilidades, guerras, desastres naturais, inundações, incêndios, sabotagens, acidentes, perda ou destruição de propriedade, intervenção por entidades governamentais, mudança nas leis, regulamentos ou ordens, ou outros eventos ou circunstâncias ou causas que fujam ao controle direto da Mix Delivery.

                        11. ISENÇÕES DE RESPONSABILIDADE
                        Os Serviços são fornecidos “como estão” e “conforme disponíveis”. A Mix Delivery não faz nenhuma declaração ou garantia em relação à confiabilidade, pontualidade, qualidade, adequação ou disponibilidade dos Serviços ou quaisquer Serviços solicitados através do uso dos Serviços, ou que os Serviços serão ininterruptos ou livres de erros.
                        A Mix Delivery não garante a qualidade, idoneidade, segurança ou capacidade de provedores terceirizados. Você concorda que todo o risco decorrente do uso dos Serviços, e qualquer serviço ou bem solicitado em relação a eles, será exclusivamente de sua responsabilidade, até o limite máximo permitido pela Legislação Aplicável.
                        A Mix Delivery não controla, gere ou dirige quaisquer provedores terceirizados. Os provedores terceirizados não são procuradores reais, procuradores aparentes, procuradores ostensivos ou funcionários da Mix Delivery.
                        A Mix Delivery não controla, endossa ou assume responsabilidade por qualquer Conteúdo do Entregador Parceiro ou conteúdo de terceiros disponível ou vinculado aos Serviços. A Mix Delivery não pode declarar e não declara ou garante que os serviços ou servidores estão livres de vírus ou outros componentes prejudiciais.
                        12. RESCISÃO DOS SERVIÇOS
                        O Entregador Parceiro poderá parar de usar os Serviços a qualquer momento. A rescisão ou exclusão da Conta do Entregador Parceiro pelo Entregador Parceiro obedecerá ao procedimento e atenderá aos requisitos definidos na Política de Offboarding do Entregador Parceiro. O Entregador Parceiros será exclusivamente responsável por se familiarizar com a Política de Offboarding do Entregador Parceiro antes de solicitar o encerramento ou exclusão de sua conta.
                        A Mix Delivery também poderá interromper o fornecimento dos Serviços a qualquer momento, ou criar limites para o uso dos Serviços, seja especificamente para o Entregador Parceiro ou em geral. O encerramento não limitará nenhum dos outros direitos ou tutelas disponíveis à Mix Delivery. As disposições destes Termos de Uso sobreviverão a qualquer rescisão de serviços. Nada nesta disposição dá à Mix Delivery o direito de interferir na capacidade do Entregador Parceiro de entrar em contato com os Usuários por conta própria e fornecer Entregas de Remessas aos Usuários, apenas o direito de impedir o uso da Plataforma pelo Entregador Parceiro.
                        13. CLÁUSULAS INDEPENDENTES
                        Qualquer disposição destes Termos de Uso que seja proibida ou inexequível em qualquer jurisdição deve, com relação a tal jurisdição e a aplicação a tais fatos e circunstâncias, ser ineficaz na medida de tal proibição ou inexequibilidade, sem invalidar as disposições restantes deste ou a sua aplicação a outros fatos e circunstâncias, e qualquer proibição ou inexequibilidade em qualquer jurisdição não invalidará ou tornará inexequível tal disposição em qualquer outra jurisdição.
                        14. SEM RENÚNCIA
                        A falha da Mix Delivery ou do Entregador Parceiro, em qualquer instância, em exigir o cumprimento estrito dos termos destes Termos de Uso ou em exercer qualquer opção sob este documento, não deverá ser interpretada como uma renúncia a tal termo ou opção e tal termo ou opção continuará em pleno vigor.
                        15. LEI APLICÁVEL
                        Salvo disposição em contrário nestes Termos de Uso, estes Termos de Uso serão regidos e interpretados exclusivamente de acordo com as leis do Brasil. Qualquer disputa, controvérsia ou ação decorrente de ou relacionada a estes Termos de Uso, ou a violação, rescisão ou invalidade dos mesmos, será resolvida pelo juízo competente na jurisdição em que você foi registrado pela Mix Delivery para realizar Entrega de Remessas.
                        16. SUCESSORES
                        Estes Termos de Uso e quaisquer direitos e licenças aqui concedidos não poderão ser transferidos ou cedidos por você, mas podem ser cedidos pela Mix Delivery sem restrição. Qualquer tentativa de transferência ou cessão em violação a este instrumento será nula e sem efeito. Estes Termos de Uso vinculam e beneficiam cada parte e seus sucessores e cessionários permitidos.
                        17. TÍTULOS
                        Os títulos utilizados nestes Termos de Uso são apenas para conveniência e não limitam, ampliam, modificam ou de outra forma afetam os termos e disposições destes Termos de Uso.
                        18. IDIOMA
                        Em caso de discrepância entre a versão em inglês e a versão em português, a versão em inglês prevalecerá.
                    </div>
                </section>
            </Wrapper>
            <Footer/>
        </>
    )
}